name: vf-recovery-webapp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy>=0.1.14
  - babel
  - bottleneck
  - cartopy>=0.19.0
  - dask
  - dask-kubernetes
  - distributed
  - flask
  - flask-sqlalchemy
  - gcsfs
  - graphviz
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab>=0.35
  - jupyterlab_launcher
  - jupyter_client
  - jupyter_server
  - lz4
  - matplotlib
  - nb_conda_kernels
  - nodejs
  - nomkl
  - numcodecs
  - parcels>=2.4.0
  - py
  - pydap
  - python-blosc
  - scikit-learn
  - shapely
  - seaborn
  - tqdm
  - watermark
  - werkzeug
  - xarray>0.16.0
  - xhistogram
  - zarr
  - pip
  - pip:
    - jupyter-server-proxy
    - netCDF4
    - erddapy
    - gitpython
    - motuclient
    - cmocean
    - progressbar
    - cgen
    - pymbolic
    - memory-profiler
    - line-profiler
    - flask-swagger
    - flask-login
    - geojson
    - dominate